name: Autograding Tests
'on':
- push
- repository_dispatch
permissions:
  checks: write
  actions: read
  contents: read
jobs:
  run-autograding-tests:
    runs-on: ubuntu-latest
    if: github.actor != 'github-classroom[bot]'
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    - name: output test
      id: output-test
      uses: classroom-resources/autograding-io-grader@v1
      with:
        test-name: output test
        setup-command: ''
        command: cd src; javac Main.java; java Main;
        input: ''
        expected-output: |-
          I do handle the teaching part !
          I do handle the teaching part !
          I do handle the MBDS Master degree
          I do handle the registrations and all the paperwork
        comparison-method: contains
        timeout: 10
    - name: Autograding Reporter
      uses: classroom-resources/autograding-grading-reporter@v1
      env:
        OUTPUT-TEST_RESULTS: "${{steps.output-test.outputs.result}}"
      with:
        runners: output-test

